const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
module.exports = async function verify(window, getState) {
  const outputArgument = process.argv.find(a => a.startsWith('--verification-output='));
  const output = outputArgument ? path.resolve(outputArgument.slice(22)) : path.resolve(__dirname, '../docs');
  fs.mkdirSync(output, { recursive: true });
  const evaluate = script => window.webContents.executeJavaScript(script);
  await evaluate("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
  assert.equal(await evaluate("document.querySelectorAll('#tree-rows tr').length"), 14);
  assert.ok(await evaluate("getComputedStyle(document.querySelector('.tile')).backgroundColor !== 'rgba(0, 0, 0, 0)'"));
  assert.ok(await evaluate("document.querySelectorAll('.folder-caption').length >= 5"));
  fs.writeFileSync(path.join(output, 'showcase.png'), (await window.webContents.capturePage()).toPNG());
  await evaluate("document.querySelector('#settings').click()");
  assert.ok(await evaluate("document.querySelector('#settings-dialog').open"));
  assert.equal(await evaluate("document.querySelector('#palette').value"), 'aurora');
  await evaluate("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
  await new Promise(resolve => setTimeout(resolve, 100));
  fs.writeFileSync(path.join(output, 'settings.png'), (await window.webContents.capturePage()).toPNG());
  await evaluate("document.querySelector('#theme').value='dark'; document.querySelector('#theme').dispatchEvent(new Event('input')); document.querySelector('#palette').value='forest'; document.querySelector('#palette').dispatchEvent(new Event('input')); document.querySelector('#settings-dialog .close-dialog').click()");
  assert.ok(await evaluate("document.body.classList.contains('dark')"));
  await evaluate("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
  await new Promise(resolve => setTimeout(resolve, 100));
  fs.writeFileSync(path.join(output, 'forest-dark.png'), (await window.webContents.capturePage()).toPNG());
  await window.webContents.reload();
  await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
  assert.ok(await evaluate("document.body.classList.contains('dark')"));
  await evaluate("document.querySelector('#reset-settings').click(); document.querySelector('#file-tab').click()");
  assert.equal(await evaluate("document.querySelectorAll('#tree-rows tr').length"), 424);
  await evaluate("document.querySelector('#search').value='.mp4'; document.querySelector('#search').dispatchEvent(new Event('input'))");
  assert.equal(await evaluate("document.querySelectorAll('#tree-rows tr').length"), 48);
  await evaluate("document.querySelector('#search').value=''; document.querySelector('#search').dispatchEvent(new Event('input')); document.querySelector('#tree-tab').click(); document.querySelector('#mark').click(); document.querySelector('#review').click()");
  assert.equal(await evaluate("document.querySelectorAll('.review-item').length"), 1);
  assert.ok(await evaluate("document.querySelector('#trash').disabled"));
  await evaluate("document.querySelector('#review-dialog .close-dialog').click(); document.querySelector('#zoom-in').click()");
  assert.equal(await evaluate("document.querySelector('#zoom').value"), '120');
  await evaluate("document.querySelector('#fit').click()");
  await evaluate("document.querySelector('#largest-files').click()");
  assert.equal(await evaluate("document.querySelectorAll('#tree-rows tr').length"), 25);
  assert.ok(await evaluate("document.querySelector('#status').textContent.includes('sample data')"));
  await evaluate("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
  fs.writeFileSync(path.join(output, 'largest-files.png'), (await window.webContents.capturePage()).toPNG());
  await evaluate("document.querySelector('#largest-files').click()");
  await evaluate("window.__originalAnchorClick = HTMLAnchorElement.prototype.click; HTMLAnchorElement.prototype.click = function(){ if(this.download === 'entree-scan-summary.json'){ window.__summaryFilename = this.download; return; } return window.__originalAnchorClick.call(this); }; window.__summaryDownload = null; const originalCreateObjectURL = URL.createObjectURL.bind(URL); URL.createObjectURL = blob => { blob.text().then(text => window.__summaryDownload = JSON.parse(text)); return originalCreateObjectURL(blob); }; document.querySelector('#export-summary').click(); new Promise(resolve => setTimeout(resolve, 50))");
  assert.equal(await evaluate("window.__summaryDownload.source"), 'sample demo data — not a live PC scan');
  assert.equal(await evaluate("window.__summaryDownload.largestFiles.length"), 25);
  assert.equal(await evaluate("window.__summaryFilename"), 'entree-scan-summary.json');
  await evaluate("document.querySelector('#theme').value='eclipse'; document.querySelector('#theme').dispatchEvent(new Event('input'))");
  await window.webContents.reload();
  await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
  assert.ok(await evaluate("document.body.classList.contains('eclipse')"));
  assert.equal(await evaluate("document.querySelector('#palette').value"), 'eclipse');
  assert.equal(await evaluate("getComputedStyle(document.body).backgroundColor"), 'rgb(16, 15, 20)');
  assert.equal(await evaluate("document.querySelector('#accent').value"), '#ffb454');
  await evaluate("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
  await new Promise(resolve => setTimeout(resolve, 100));
  fs.writeFileSync(path.join(output, 'eclipse.png'), (await window.webContents.capturePage()).toPNG());
  await evaluate("document.querySelector('#theme').value='aurora'; document.querySelector('#theme').dispatchEvent(new Event('input'))");
  await window.webContents.reload();
  await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
  assert.ok(await evaluate("document.body.classList.contains('aurora')"));
  assert.match(await evaluate("getComputedStyle(document.body).backgroundImage"), /aurora-violet\.png/);
  assert.ok(await evaluate("new Promise(resolve => { const image = new Image(); image.onload = () => resolve(image.naturalWidth > 1000); image.onerror = () => resolve(false); image.src = 'assets/aurora-violet.png'; })"), 'Bundled Aurora background must load');
  await evaluate("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
  await new Promise(resolve => setTimeout(resolve, 200));
  fs.writeFileSync(path.join(output, 'aurora.png'), (await window.webContents.capturePage()).toPNG());
  console.log('Verified Aurora theme and bundled background.');
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'entree-native-'));
  try {
    fs.mkdirSync(path.join(root, 'Projects')); fs.writeFileSync(path.join(root, 'Projects', 'code.js'), Buffer.alloc(8192)); fs.writeFileSync(path.join(root, 'note.txt'), 'ENTree');
    console.log('Starting temporary-directory scan.');
    await evaluate(`window.entree.scan(${JSON.stringify(root)}, {hidden:true})`);
    const start = Date.now();
    while (!getState().result && Date.now() - start < 15000) await new Promise(resolve => setTimeout(resolve, 100));
    const state = getState(); assert.ok(state.result, 'Native worker scan must finish');
    console.log('Temporary-directory scan completed.');
    assert.equal(state.result.tree.size, 8198);
    assert.ok(state.result.tree.allocated !== null, 'Allocated storage must be available on this platform');
    console.log('Verified native scan totals and allocated bytes.');
    await evaluate("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
    assert.equal(await evaluate("document.querySelector('#source-badge').textContent"), 'LOCAL · PRIVATE');
    console.log('Verified local-source badge.');
    assert.equal(await evaluate("document.querySelectorAll('#extension-rows tr').length"), 2);
    console.log('Verified extension summary.');
    await evaluate("window.__originalAnchorClick = HTMLAnchorElement.prototype.click; HTMLAnchorElement.prototype.click = function(){ if(this.download === 'entree-scan-summary.json'){ window.__summaryFilename = this.download; return; } return window.__originalAnchorClick.call(this); }; window.__summaryDownload = null; const originalCreateObjectURL = URL.createObjectURL.bind(URL); URL.createObjectURL = blob => { blob.text().then(text => window.__summaryDownload = JSON.parse(text)); return originalCreateObjectURL(blob); }; null");
    await evaluate("document.querySelector('#export-summary').click(); new Promise(resolve => setTimeout(resolve, 150))");
    console.log('Triggered summary export in the test harness.');
    assert.equal(await evaluate("window.__summaryDownload.source"), 'local scan');
    console.log('Verified local-scan export source.');
    assert.equal(await evaluate("window.__summaryDownload.root"), root);
    console.log('Verified scan-summary export metadata.');
    await evaluate("document.querySelector('#largest-files').click()");
    assert.equal(await evaluate("document.querySelectorAll('#tree-rows tr').length"), 2);
    const rootTrash = await evaluate(`window.entree.trash([${JSON.stringify(state.root)}]).then(()=> 'unexpected success').catch(error => error.message)`);
    assert.match(rootTrash, /scan root/);
    fs.writeFileSync(path.join(output, 'native-scan.png'), (await window.webContents.capturePage()).toPNG());
  } finally { fs.rmSync(root, { recursive: true, force: true }); }
  console.log('Native verification passed: settings persistence, tables/search, top-files view, summary export, review, zoom, worker scan, allocation and root protection.');
  fs.writeFileSync(path.join(output, 'verification.json'), JSON.stringify({ passed: true, platform: process.platform, nativeScan: true, allocatedBytes: true, settingsPersistence: true, search: true, largestFiles: true, summaryExport: true, review: true, zoom: true, rootProtection: true }, null, 2));
};
