const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
module.exports = async function verify(window, getState) {
  const outputArgument = process.argv.find(a => a.startsWith('--verification-output='));
  const output = outputArgument ? path.resolve(outputArgument.slice(22)) : path.resolve(__dirname, '../docs');
  fs.mkdirSync(output, { recursive: true });
  const evaluate = script => window.webContents.executeJavaScript(script);
  await evaluate("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
  assert.equal(await evaluate("document.querySelectorAll('#tree-rows tr').length"), 14);
  assert.ok(await evaluate("getComputedStyle(document.querySelector('.tile')).backgroundColor !== 'rgba(0, 0, 0, 0)'"));
  assert.ok(await evaluate("document.querySelectorAll('.folder-caption').length >= 5"));
  fs.writeFileSync(path.join(output, 'showcase.png'), (await window.webContents.capturePage()).toPNG());
  await evaluate("document.querySelector('#settings').click()");
  assert.ok(await evaluate("document.querySelector('#settings-dialog').open"));
  await evaluate("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
  await new Promise(resolve => setTimeout(resolve, 100));
  fs.writeFileSync(path.join(output, 'settings.png'), (await window.webContents.capturePage()).toPNG());
  await evaluate("document.querySelector('#theme').value='dark'; document.querySelector('#theme').dispatchEvent(new Event('input')); document.querySelector('#palette').value='forest'; document.querySelector('#palette').dispatchEvent(new Event('input')); document.querySelector('#settings-dialog .close-dialog').click()");
  assert.ok(await evaluate("document.body.classList.contains('dark')"));
  await evaluate("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
  await new Promise(resolve => setTimeout(resolve, 100));
  fs.writeFileSync(path.join(output, 'forest-dark.png'), (await window.webContents.capturePage()).toPNG());
  await window.webContents.reload();
  await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
  assert.ok(await evaluate("document.body.classList.contains('dark')"));
  await evaluate("document.querySelector('#reset-settings').click(); document.querySelector('#file-tab').click()");
  assert.equal(await evaluate("document.querySelectorAll('#tree-rows tr').length"), 424);
  await evaluate("document.querySelector('#search').value='.mp4'; document.querySelector('#search').dispatchEvent(new Event('input'))");
  assert.equal(await evaluate("document.querySelectorAll('#tree-rows tr').length"), 48);
  await evaluate("document.querySelector('#search').value=''; document.querySelector('#search').dispatchEvent(new Event('input')); document.querySelector('#tree-tab').click(); document.querySelector('#mark').click(); document.querySelector('#review').click()");
  assert.equal(await evaluate("document.querySelectorAll('.review-item').length"), 1);
  assert.ok(await evaluate("document.querySelector('#trash').disabled"));
  await evaluate("document.querySelector('#review-dialog .close-dialog').click(); document.querySelector('#zoom-in').click()");
  assert.equal(await evaluate("document.querySelector('#zoom').value"), '120');
  await evaluate("document.querySelector('#fit').click()");
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'entree-native-'));
  try {
    fs.mkdirSync(path.join(root, 'Projects')); fs.writeFileSync(path.join(root, 'Projects', 'code.js'), Buffer.alloc(8192)); fs.writeFileSync(path.join(root, 'note.txt'), 'ENTree');
    await evaluate(`window.entree.scan(${JSON.stringify(root)}, {hidden:true})`);
    const start = Date.now();
    while (!getState().result && Date.now() - start < 15000) await new Promise(resolve => setTimeout(resolve, 100));
    const state = getState(); assert.ok(state.result, 'Native worker scan must finish');
    assert.equal(state.result.tree.size, 8198);
    assert.ok(state.result.tree.allocated !== null, 'Allocated storage must be available on this platform');
    await evaluate("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
    assert.equal(await evaluate("document.querySelector('#source-badge').textContent"), 'LOCAL · PRIVATE');
    assert.equal(await evaluate("document.querySelectorAll('#extension-rows tr').length"), 2);
    const rootTrash = await evaluate(`window.entree.trash([${JSON.stringify(state.root)}]).then(()=> 'unexpected success').catch(error => error.message)`);
    assert.match(rootTrash, /scan root/);
    fs.writeFileSync(path.join(output, 'native-scan.png'), (await window.webContents.capturePage()).toPNG());
  } finally { fs.rmSync(root, { recursive: true, force: true }); }
  console.log('Native verification passed: settings persistence, tables/search, review, zoom, worker scan, allocation and root protection.');
  fs.writeFileSync(path.join(output, 'verification.json'), JSON.stringify({ passed: true, platform: process.platform, nativeScan: true, allocatedBytes: true, settingsPersistence: true, search: true, review: true, zoom: true, rootProtection: true }, null, 2));
};
